name: utilities
description: Utilities for all projects
version: 0.0.1
homepage: Farzad

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  file_picker: ^8.0.3
  flutter_svg: ^2.0.9
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.2.6
  share_plus: ^7.1.0
  #  shamsi_date: ^1.0.2
  persian_datetime_picker: ^2.6.0
  flutter_colorpicker: ^1.0.3
  logger: ^2.2.0
  lottie: ^3.1.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.1
  flutter_typeahead: ^4.8.0
  package_info_plus: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: ir.bestdroid.utilities
        pluginClass: UtilitiesPlugin
      ios:
        pluginClass: UtilitiesPlugin
      windows:
        pluginClass: UtilitiesPluginCApi
      web:
        pluginClass: UtilitiesWeb
        fileName: utilities_web.dart


  assets:
    - lib/assets/svg/
    - lib/assets/png/
    - lib/assets/jpg/